# Diaspora [Production]
# Diaspora main directory is mounted for the host (see volume)

version: '3'

services:

  diaspora:
    image: diaspora.inethi.net:1.0
    volume:
      - /mnt/data/diaspora/uploads:/home/diaspora/diaspora/public/uploads
    ports:
      - 8083:443
    restart: on-failure
    network_mode: "bridge"
    container_name: diaspora.inethi.net
    hostname: diaspora.inethi.net
    domainname: diaspora.inethi.net
    privileged: true