# Diaspora [Production]
# Diaspora main directory is mounted for the host (see volume)

version: '3'

services:

  diaspora:
    image: diaspora.inethi.net
    volumes:
      - /mnt/data/diaspora/nginx:/etc/nginx
      - /mnt/data/diaspora/diaspora:/home/diaspora/diaspora
    ports:
      - 443:443
    restart: on-failure
    network_mode: "bridge"
    container_name: diaspora.inethi.net
    hostname: diaspora.inethi.net
    domainname: diaspora.inethi.net
    privileged: true